url: https://gabrielbacha.github.io
baseurl: /Jekyll-TailwindCSS-Starter-Template
title: 'Jekyll TailwindCSS'

plugins:
  - jekyll-postcss
  - jekyll-sitemap # Adds sitemap to the website at /sitemap.xml
  # - jekyll-feed # Adds feed to the website at /feed.xml
  # - jekyll-paginate # Used for sorting posts by page numbers.
  - jekyll-seo-tag # Adds all the important SEO meta tags by default.

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - .git
  - vendor

include:
  - _pages


sass:
  sass_dir: /assets/css/_sass
  style: compressed


destination: zzz

markdown: kramdown
